export interface Game {
  id: string;
  name: string;
  releaseYear: number;
  domain: string;
}

export const GAMES: Game[] = [
  // Nintendo Classics & Modern
  {
    id: 'zelda-botw',
    name: 'The Legend of Zelda: Breath of the Wild',
    releaseYear: 2017,
    domain: 'zelda.com',
  },
  {
    id: 'zelda-totk',
    name: 'The Legend of Zelda: Tears of the Kingdom',
    releaseYear: 2023,
    domain: 'zelda.com',
  },
  {
    id: 'zelda-ocarina',
    name: 'The Legend of Zelda: Ocarina of Time',
    releaseYear: 1998,
    domain: 'zelda.com',
  },
  {
    id: 'zelda-majora',
    name: "The Legend of Zelda: Majora's Mask",
    releaseYear: 2000,
    domain: 'zelda.com',
  },
  {
    id: 'zelda-wind-waker',
    name: 'The Legend of Zelda: The Wind Waker',
    releaseYear: 2002,
    domain: 'zelda.com',
  },
  {
    id: 'zelda-twilight',
    name: 'The Legend of Zelda: Twilight Princess',
    releaseYear: 2006,
    domain: 'zelda.com',
  },
  {
    id: 'zelda-link-to-past',
    name: 'The Legend of Zelda: A Link to the Past',
    releaseYear: 1991,
    domain: 'zelda.com',
  },
  {
    id: 'super-mario-64',
    name: 'Super Mario 64',
    releaseYear: 1996,
    domain: 'mario.nintendo.com',
  },
  {
    id: 'super-mario-odyssey',
    name: 'Super Mario Odyssey',
    releaseYear: 2017,
    domain: 'mario.nintendo.com',
  },
  {
    id: 'super-mario-galaxy',
    name: 'Super Mario Galaxy',
    releaseYear: 2007,
    domain: 'mario.nintendo.com',
  },
  {
    id: 'super-mario-galaxy-2',
    name: 'Super Mario Galaxy 2',
    releaseYear: 2010,
    domain: 'mario.nintendo.com',
  },
  {
    id: 'super-mario-world',
    name: 'Super Mario World',
    releaseYear: 1990,
    domain: 'mario.nintendo.com',
  },
  {
    id: 'super-mario-bros-3',
    name: 'Super Mario Bros. 3',
    releaseYear: 1988,
    domain: 'mario.nintendo.com',
  },
  {
    id: 'mario-kart-8',
    name: 'Mario Kart 8 Deluxe',
    releaseYear: 2017,
    domain: 'mario.nintendo.com',
  },
  {
    id: 'super-smash-bros-melee',
    name: 'Super Smash Bros. Melee',
    releaseYear: 2001,
    domain: 'smashbros.com',
  },
  {
    id: 'super-smash-bros-ult',
    name: 'Super Smash Bros. Ultimate',
    releaseYear: 2018,
    domain: 'smashbros.com',
  },
  {
    id: 'pokemon-red-blue',
    name: 'Pokémon Red & Blue',
    releaseYear: 1996,
    domain: 'pokemon.com',
  },
  {
    id: 'pokemon-gold-silver',
    name: 'Pokémon Gold & Silver',
    releaseYear: 1999,
    domain: 'pokemon.com',
  },
  {
    id: 'pokemon-emerald',
    name: 'Pokémon Emerald',
    releaseYear: 2004,
    domain: 'pokemon.com',
  },
  {
    id: 'pokemon-hgss',
    name: 'Pokémon HeartGold & SoulSilver',
    releaseYear: 2009,
    domain: 'pokemon.com',
  },
  {
    id: 'metroid-prime',
    name: 'Metroid Prime',
    releaseYear: 2002,
    domain: 'nintendo.com',
  },
  {
    id: 'super-metroid',
    name: 'Super Metroid',
    releaseYear: 1994,
    domain: 'nintendo.com',
  },
  {
    id: 'earthbound',
    name: 'EarthBound',
    releaseYear: 1994,
    domain: 'nintendo.com',
  },
  {
    id: 'animal-crossing-nh',
    name: 'Animal Crossing: New Horizons',
    releaseYear: 2020,
    domain: 'animal-crossing.com',
  },
  {
    id: 'fire-emblem-three-houses',
    name: 'Fire Emblem: Three Houses',
    releaseYear: 2019,
    domain: 'nintendo.com',
  },

  // FromSoft & Souls-likes
  {
    id: 'dark-souls',
    name: 'Dark Souls',
    releaseYear: 2011,
    domain: 'bandainamcoent.com',
  },
  {
    id: 'dark-souls-3',
    name: 'Dark Souls III',
    releaseYear: 2016,
    domain: 'bandainamcoent.com',
  },
  {
    id: 'bloodborne',
    name: 'Bloodborne',
    releaseYear: 2015,
    domain: 'playstation.com',
  },
  {
    id: 'sekiro',
    name: 'Sekiro: Shadows Die Twice',
    releaseYear: 2019,
    domain: 'activision.com',
  },
  {
    id: 'elden-ring',
    name: 'Elden Ring',
    releaseYear: 2022,
    domain: 'bandainamcoent.com',
  },
  {
    id: 'demon-souls',
    name: "Demon's Souls",
    releaseYear: 2009,
    domain: 'playstation.com',
  },
  {
    id: 'hollow-knight',
    name: 'Hollow Knight',
    releaseYear: 2017,
    domain: 'teamcherry.com.au',
  },
  {
    id: 'blasphemous',
    name: 'Blasphemous',
    releaseYear: 2019,
    domain: 'team17.com',
  },

  // PlayStation Staples
  {
    id: 'tlou',
    name: 'The Last of Us',
    releaseYear: 2013,
    domain: 'playstation.com',
  },
  {
    id: 'tlou-2',
    name: 'The Last of Us Part II',
    releaseYear: 2020,
    domain: 'playstation.com',
  },
  {
    id: 'god-of-war-2018',
    name: 'God of War',
    releaseYear: 2018,
    domain: 'playstation.com',
  },
  {
    id: 'god-of-war-ragnarok',
    name: 'God of War Ragnarök',
    releaseYear: 2022,
    domain: 'playstation.com',
  },
  {
    id: 'ghost-of-tsushima',
    name: 'Ghost of Tsushima',
    releaseYear: 2020,
    domain: 'playstation.com',
  },
  {
    id: 'spiderman-2018',
    name: "Marvel's Spider-Man",
    releaseYear: 2018,
    domain: 'insomniac.games',
  },
  {
    id: 'horizon-zero-dawn',
    name: 'Horizon Zero Dawn',
    releaseYear: 2017,
    domain: 'playstation.com',
  },
  {
    id: 'uncharted-2',
    name: 'Uncharted 2: Among Thieves',
    releaseYear: 2009,
    domain: 'naughtydog.com',
  },
  {
    id: 'uncharted-4',
    name: "Uncharted 4: A Thief's End",
    releaseYear: 2016,
    domain: 'naughtydog.com',
  },
  {
    id: 'shadow-of-the-colossus',
    name: 'Shadow of the Colossus',
    releaseYear: 2005,
    domain: 'playstation.com',
  },
  {
    id: 'bloodborne-2',
    name: 'Bloodborne 2 (Wait What)',
    releaseYear: 2099,
    domain: 'playstation.com',
  }, // Just kidding
  {
    id: 'persona-5-royal',
    name: 'Persona 5 Royal',
    releaseYear: 2019,
    domain: 'atlus.com',
  },
  {
    id: 'persona-4-golden',
    name: 'Persona 4 Golden',
    releaseYear: 2012,
    domain: 'atlus.com',
  },
  {
    id: 'ff7-original',
    name: 'Final Fantasy VII',
    releaseYear: 1997,
    domain: 'finalfantasyvii.com',
  },
  {
    id: 'ff7-remake',
    name: 'Final Fantasy VII Remake',
    releaseYear: 2020,
    domain: 'finalfantasyvii.com',
  },
  {
    id: 'ffxiv',
    name: 'Final Fantasy XIV',
    releaseYear: 2013,
    domain: 'finalfantasyxiv.com',
  },
  {
    id: 'ffx',
    name: 'Final Fantasy X',
    releaseYear: 2001,
    domain: 'finalfantasy.com',
  },
  {
    id: 'metal-gear-solid',
    name: 'Metal Gear Solid',
    releaseYear: 1998,
    domain: 'konami.com',
  },
  {
    id: 'mgs-3',
    name: 'Metal Gear Solid 3: Snake Eater',
    releaseYear: 2004,
    domain: 'konami.com',
  },
  {
    id: 'castlevania-sotn',
    name: 'Castlevania: Symphony of the Night',
    releaseYear: 1997,
    domain: 'konami.com',
  },
  {
    id: 'silent-hill-2',
    name: 'Silent Hill 2',
    releaseYear: 2001,
    domain: 'konami.com',
  },
  {
    id: 'resident-evil-4',
    name: 'Resident Evil 4',
    releaseYear: 2005,
    domain: 'capcom.com',
  },
  {
    id: 'resident-evil-2-remake',
    name: 'Resident Evil 2 Remake',
    releaseYear: 2019,
    domain: 'capcom.com',
  },

  // Rockstar & Open World Titans
  {
    id: 'gta-v',
    name: 'Grand Theft Auto V',
    releaseYear: 2013,
    domain: 'rockstargames.com',
  },
  {
    id: 'gta-sa',
    name: 'Grand Theft Auto: San Andreas',
    releaseYear: 2004,
    domain: 'rockstargames.com',
  },
  {
    id: 'gta-iv',
    name: 'Grand Theft Auto IV',
    releaseYear: 2008,
    domain: 'rockstargames.com',
  },
  {
    id: 'rdr',
    name: 'Red Dead Redemption',
    releaseYear: 2010,
    domain: 'rockstargames.com',
  },
  {
    id: 'rdr2',
    name: 'Red Dead Redemption 2',
    releaseYear: 2018,
    domain: 'rockstargames.com',
  },
  {
    id: 'witcher-3',
    name: 'The Witcher 3: Wild Hunt',
    releaseYear: 2015,
    domain: 'thewitcher.com',
  },
  {
    id: 'cyberpunk-2077',
    name: 'Cyberpunk 2077',
    releaseYear: 2020,
    domain: 'cyberpunk.net',
  },
  {
    id: 'skyrim',
    name: 'The Elder Scrolls V: Skyrim',
    releaseYear: 2011,
    domain: 'elderscrolls.bethesda.net',
  },
  {
    id: 'oblivion',
    name: 'The Elder Scrolls IV: Oblivion',
    releaseYear: 2006,
    domain: 'elderscrolls.bethesda.net',
  },
  {
    id: 'morrowind',
    name: 'The Elder Scrolls III: Morrowind',
    releaseYear: 2002,
    domain: 'elderscrolls.bethesda.net',
  },
  {
    id: 'fallout-new-vegas',
    name: 'Fallout: New Vegas',
    releaseYear: 2010,
    domain: 'fallout.bethesda.net',
  },
  {
    id: 'fallout-3',
    name: 'Fallout 3',
    releaseYear: 2008,
    domain: 'fallout.bethesda.net',
  },

  // RPGs & Story
  {
    id: 'mass-effect-2',
    name: 'Mass Effect 2',
    releaseYear: 2010,
    domain: 'ea.com',
  },
  {
    id: 'kotor',
    name: 'Star Wars: Knights of the Old Republic',
    releaseYear: 2003,
    domain: 'lucasfilm.com',
  },
  {
    id: 'disco-elysium',
    name: 'Disco Elysium',
    releaseYear: 2019,
    domain: 'zaumstudio.com',
  },
  {
    id: 'baldur-gate-3',
    name: "Baldur's Gate 3",
    releaseYear: 2023,
    domain: 'larian.com',
  },
  {
    id: 'chrono-trigger',
    name: 'Chrono Trigger',
    releaseYear: 1995,
    domain: 'square-enix.com',
  },
  {
    id: 'nier-automata',
    name: 'NieR:Automata',
    releaseYear: 2017,
    domain: 'square-enix.com',
  },
  {
    id: 'undertale',
    name: 'Undertale',
    releaseYear: 2015,
    domain: 'undertale.com',
  },
  {
    id: 'outer-wilds',
    name: 'Outer Wilds',
    releaseYear: 2019,
    domain: 'mobiusdigitalgames.com',
  },
  {
    id: 'journey',
    name: 'Journey',
    releaseYear: 2012,
    domain: 'thatgamecompany.com',
  },
  { id: 'bioshock', name: 'BioShock', releaseYear: 2007, domain: '2k.com' },
  {
    id: 'bioshock-infinite',
    name: 'BioShock Infinite',
    releaseYear: 2013,
    domain: '2k.com',
  },

  // Shooters
  {
    id: 'halo-ce',
    name: 'Halo: Combat Evolved',
    releaseYear: 2001,
    domain: 'halowaypoint.com',
  },
  {
    id: 'halo-2',
    name: 'Halo 2',
    releaseYear: 2004,
    domain: 'halowaypoint.com',
  },
  {
    id: 'halo-3',
    name: 'Halo 3',
    releaseYear: 2007,
    domain: 'halowaypoint.com',
  },
  {
    id: 'half-life',
    name: 'Half-Life',
    releaseYear: 1998,
    domain: 'half-life.com',
  },
  {
    id: 'half-life-2',
    name: 'Half-Life 2',
    releaseYear: 2004,
    domain: 'half-life.com',
  },
  {
    id: 'portal',
    name: 'Portal',
    releaseYear: 2007,
    domain: 'thinkwithportals.com',
  },
  {
    id: 'portal-2',
    name: 'Portal 2',
    releaseYear: 2011,
    domain: 'thinkwithportals.com',
  },
  {
    id: 'doom-1993',
    name: 'DOOM',
    releaseYear: 1993,
    domain: 'slayersclub.bethesda.net',
  },
  {
    id: 'doom-2016',
    name: 'DOOM',
    releaseYear: 2016,
    domain: 'slayersclub.bethesda.net',
  },
  {
    id: 'doom-eternal',
    name: 'DOOM Eternal',
    releaseYear: 2020,
    domain: 'slayersclub.bethesda.net',
  },
  {
    id: 'csgo',
    name: 'Counter-Strike: Global Offensive',
    releaseYear: 2012,
    domain: 'counter-strike.net',
  },
  {
    id: 'valorant',
    name: 'Valorant',
    releaseYear: 2020,
    domain: 'playvalorant.com',
  },
  {
    id: 'overwatch',
    name: 'Overwatch',
    releaseYear: 2016,
    domain: 'playoverwatch.com',
  },
  {
    id: 'team-fortress-2',
    name: 'Team Fortress 2',
    releaseYear: 2007,
    domain: 'teamfortress.com',
  },
  {
    id: 'destiny-2',
    name: 'Destiny 2',
    releaseYear: 2017,
    domain: 'bungie.net',
  },
  {
    id: 'apex-legends',
    name: 'Apex Legends',
    releaseYear: 2019,
    domain: 'ea.com',
  },
  {
    id: 'titanfall-2',
    name: 'Titanfall 2',
    releaseYear: 2016,
    domain: 'ea.com',
  },

  // Esports & Multiplayer
  {
    id: 'league-of-legends',
    name: 'League of Legends',
    releaseYear: 2009,
    domain: 'leagueoflegends.com',
  },
  { id: 'dota-2', name: 'Dota 2', releaseYear: 2013, domain: 'dota2.com' },
  {
    id: 'world-of-warcraft',
    name: 'World of Warcraft',
    releaseYear: 2004,
    domain: 'worldofwarcraft.com',
  },
  {
    id: 'rocket-league',
    name: 'Rocket League',
    releaseYear: 2015,
    domain: 'rocketleague.com',
  },
  {
    id: 'fortnite',
    name: 'Fortnite',
    releaseYear: 2017,
    domain: 'fortnite.com',
  },
  {
    id: 'pubg',
    name: 'PUBG: Battlegrounds',
    releaseYear: 2017,
    domain: 'pubg.com',
  },
  {
    id: 'rainbow-six-siege',
    name: "Tom Clancy's Rainbow Six Siege",
    releaseYear: 2015,
    domain: 'ubisoft.com',
  },
  {
    id: 'starcraft-bw',
    name: 'StarCraft: Brood War',
    releaseYear: 1998,
    domain: 'starcraft.com',
  },
  {
    id: 'starcraft-2',
    name: 'StarCraft II',
    releaseYear: 2010,
    domain: 'starcraft2.com',
  },
  {
    id: 'street-fighter-2',
    name: 'Street Fighter II',
    releaseYear: 1991,
    domain: 'streetfighter.com',
  },
  {
    id: 'street-fighter-6',
    name: 'Street Fighter 6',
    releaseYear: 2023,
    domain: 'streetfighter.com',
  },
  {
    id: 'tekken-3',
    name: 'Tekken 3',
    releaseYear: 1997,
    domain: 'bandainamcoent.com',
  },
  {
    id: 'tekken-8',
    name: 'Tekken 8',
    releaseYear: 2024,
    domain: 'bandainamcoent.com',
  },
  {
    id: 'guilty-gear-strive',
    name: 'Guilty Gear -Strive-',
    releaseYear: 2021,
    domain: 'arcsystemworks.com',
  },

  // Indies & Sandbox
  {
    id: 'minecraft',
    name: 'Minecraft',
    releaseYear: 2011,
    domain: 'minecraft.net',
  },
  {
    id: 'terraria',
    name: 'Terraria',
    releaseYear: 2011,
    domain: 'terraria.org',
  },
  {
    id: 'stardew-valley',
    name: 'Stardew Valley',
    releaseYear: 2016,
    domain: 'stardewvalley.net',
  },
  {
    id: 'celeste',
    name: 'Celeste',
    releaseYear: 2018,
    domain: 'celestegame.com',
  },
  {
    id: 'hades',
    name: 'Hades',
    releaseYear: 2020,
    domain: 'supergiantgames.com',
  },
  {
    id: 'dead-cells',
    name: 'Dead Cells',
    releaseYear: 2018,
    domain: 'motion-twin.com',
  },
  {
    id: 'spelunky-2',
    name: 'Spelunky 2',
    releaseYear: 2020,
    domain: 'spelunkyworld.com',
  },
  {
    id: 'return-of-the-obra-dinn',
    name: 'Return of the Obra Dinn',
    releaseYear: 2018,
    domain: 'obradinn.com',
  },
  {
    id: 'papers-please',
    name: 'Papers, Please',
    releaseYear: 2013,
    domain: 'papersplea.se',
  },
  {
    id: 'factorio',
    name: 'Factorio',
    releaseYear: 2020,
    domain: 'factorio.com',
  },
  { id: 'rimworld', name: 'RimWorld', releaseYear: 2018, domain: 'ludeon.com' },
  {
    id: 'slay-the-spire',
    name: 'Slay the Spire',
    releaseYear: 2019,
    domain: 'megacrit.com',
  },
  {
    id: 'binding-of-isaac',
    name: 'The Binding of Isaac: Rebirth',
    releaseYear: 2014,
    domain: 'nicalis.com',
  },
  {
    id: 'cuphead',
    name: 'Cuphead',
    releaseYear: 2017,
    domain: 'studiomdhr.com',
  },

  // Classic Arcade & PC Strategy
  { id: 'tetris', name: 'Tetris', releaseYear: 1984, domain: 'tetris.com' },
  { id: 'pac-man', name: 'Pac-Man', releaseYear: 1980, domain: 'pacman.com' },
  {
    id: 'space-invaders',
    name: 'Space Invaders',
    releaseYear: 1978,
    domain: 'taito.co.jp',
  },
  {
    id: 'donkey-kong',
    name: 'Donkey Kong',
    releaseYear: 1981,
    domain: 'nintendo.com',
  },
  {
    id: 'age-of-empires-2',
    name: 'Age of Empires II',
    releaseYear: 1999,
    domain: 'ageofempires.com',
  },
  {
    id: 'civ-5',
    name: "Sid Meier's Civilization V",
    releaseYear: 2010,
    domain: 'civilization.com',
  },
  {
    id: 'civ-6',
    name: "Sid Meier's Civilization VI",
    releaseYear: 2016,
    domain: 'civilization.com',
  },
  {
    id: 'xcom-enemy-unknown',
    name: 'XCOM: Enemy Unknown',
    releaseYear: 2012,
    domain: 'xcom.com',
  },
  { id: 'xcom-2', name: 'XCOM 2', releaseYear: 2016, domain: 'xcom.com' },
  { id: 'sims-2', name: 'The Sims 2', releaseYear: 2004, domain: 'ea.com' },
  { id: 'sims-4', name: 'The Sims 4', releaseYear: 2014, domain: 'ea.com' },
  {
    id: 'rollercoaster-tycoon',
    name: 'RollerCoaster Tycoon',
    releaseYear: 1999,
    domain: 'atari.com',
  },

  // Random / Miscellaneous
  {
    id: 'wii-sports',
    name: 'Wii Sports',
    releaseYear: 2006,
    domain: 'nintendo.com',
  },
  {
    id: 'guitar-hero-3',
    name: 'Guitar Hero III: Legends of Rock',
    releaseYear: 2007,
    domain: 'activision.com',
  },
  {
    id: 'rock-band',
    name: 'Rock Band',
    releaseYear: 2007,
    domain: 'harmonixmusic.com',
  },
  {
    id: 'tony-hawk-pro-skater-2',
    name: "Tony Hawk's Pro Skater 2",
    releaseYear: 2000,
    domain: 'activision.com',
  },
  { id: 'yakuza-0', name: 'Yakuza 0', releaseYear: 2015, domain: 'sega.com' },
  {
    id: 'devil-may-cry-5',
    name: 'Devil May Cry 5',
    releaseYear: 2019,
    domain: 'capcom.com',
  },
  { id: 'okami', name: 'Ōkami', releaseYear: 2006, domain: 'capcom.com' },
  {
    id: 'goldeneye-007',
    name: 'GoldenEye 007',
    releaseYear: 1997,
    domain: 'nintendo.com',
  },
  {
    id: 'perfect-dark',
    name: 'Perfect Dark',
    releaseYear: 2000,
    domain: 'rare.co.uk',
  },
  {
    id: 'banjo-kazooie',
    name: 'Banjo-Kazooie',
    releaseYear: 1998,
    domain: 'rare.co.uk',
  },
  {
    id: 'conker-bad-fur-day',
    name: "Conker's Bad Fur Day",
    releaseYear: 2001,
    domain: 'rare.co.uk',
  },
  {
    id: 'diablo-2',
    name: 'Diablo II',
    releaseYear: 2000,
    domain: 'blizzard.com',
  },

  // Call of Duty & Modern Shooters
  {
    id: 'cod-4',
    name: 'Call of Duty 4: Modern Warfare',
    releaseYear: 2007,
    domain: 'callofduty.com',
  },
  {
    id: 'cod-mw2',
    name: 'Call of Duty: Modern Warfare 2',
    releaseYear: 2009,
    domain: 'callofduty.com',
  },
  {
    id: 'cod-bo1',
    name: 'Call of Duty: Black Ops',
    releaseYear: 2010,
    domain: 'callofduty.com',
  },
  {
    id: 'cod-bo2',
    name: 'Call of Duty: Black Ops II',
    releaseYear: 2012,
    domain: 'callofduty.com',
  },
  {
    id: 'cod-waw',
    name: 'Call of Duty: World at War',
    releaseYear: 2008,
    domain: 'callofduty.com',
  },
  {
    id: 'cod-warzone',
    name: 'Call of Duty: Warzone',
    releaseYear: 2020,
    domain: 'callofduty.com',
  },

  // PC Strategy & RPG Classics
  {
    id: 'warcraft-3',
    name: 'Warcraft III: Reign of Chaos',
    releaseYear: 2002,
    domain: 'war3.blizzard.com',
  },
  {
    id: 'diablo-1',
    name: 'Diablo',
    releaseYear: 1996,
    domain: 'diablo.blizzard.com',
  },
  {
    id: 'cc-red-alert-2',
    name: 'Command & Conquer: Red Alert 2',
    releaseYear: 2000,
    domain: 'cnc.ea.com',
  },
  {
    id: 'age-of-mythology',
    name: 'Age of Mythology',
    releaseYear: 2002,
    domain: 'ageofempires.com',
  },
  {
    id: 'deus-ex-original',
    name: 'Deus Ex',
    releaseYear: 2000,
    domain: 'eidos.com',
  },
  {
    id: 'system-shock-2',
    name: 'System Shock 2',
    releaseYear: 1999,
    domain: 'nightdivestudios.com',
  },
  {
    id: 'fallout-1',
    name: 'Fallout',
    releaseYear: 1997,
    domain: 'fallout.bethesda.net',
  },
  {
    id: 'fallout-2',
    name: 'Fallout 2',
    releaseYear: 1998,
    domain: 'fallout.bethesda.net',
  },
  {
    id: 'fallout-4',
    name: 'Fallout 4',
    releaseYear: 2015,
    domain: 'fallout.bethesda.net',
  },
  {
    id: 'simcity-2000',
    name: 'SimCity 2000',
    releaseYear: 1993,
    domain: 'ea.com',
  },
  {
    id: 'rct-2',
    name: 'RollerCoaster Tycoon 2',
    releaseYear: 2002,
    domain: 'atari.com',
  },
  {
    id: 'osrs',
    name: 'Old School RuneScape',
    releaseYear: 2013,
    domain: 'runescape.com',
  },

  // Console Classics & Action Hits
  {
    id: 'metal-gear-solid-2',
    name: 'Metal Gear Solid 2: Sons of Liberty',
    releaseYear: 2001,
    domain: 'konami.com',
  },
  {
    id: 'mgs-v',
    name: 'Metal Gear Solid V: The Phantom Pain',
    releaseYear: 2015,
    domain: 'konami.com',
  },
  {
    id: 'uncharted-1',
    name: "Uncharted: Drake's Fortune",
    releaseYear: 2007,
    domain: 'naughtydog.com',
  },
  {
    id: 'uncharted-3',
    name: "Uncharted 3: Drake's Deception",
    releaseYear: 2011,
    domain: 'naughtydog.com',
  },
  {
    id: 'mortal-kombat-2',
    name: 'Mortal Kombat II',
    releaseYear: 1993,
    domain: 'mortalkombat.com',
  },
  {
    id: 'umk3',
    name: 'Ultimate Mortal Kombat 3',
    releaseYear: 1995,
    domain: 'mortalkombat.com',
  },
  {
    id: 'crash-bandicoot-original',
    name: 'Crash Bandicoot',
    releaseYear: 1996,
    domain: 'activision.com',
  },
  {
    id: 'crash-n-sane',
    name: 'Crash Bandicoot N. Sane Trilogy',
    releaseYear: 2017,
    domain: 'activision.com',
  },
  {
    id: 'spyro-original',
    name: 'Spyro the Dragon',
    releaseYear: 1998,
    domain: 'spyrothedragon.com',
  },
  {
    id: 'ratchet-clank-original',
    name: 'Ratchet & Clank',
    releaseYear: 2002,
    domain: 'insomniac.games',
  },
  {
    id: 'jak-daxter-original',
    name: 'Jak and Daxter: The Precursor Legacy',
    releaseYear: 2001,
    domain: 'naughtydog.com',
  },
  {
    id: 'thug-1',
    name: "Tony Hawk's Underground",
    releaseYear: 2003,
    domain: 'activision.com',
  },
  {
    id: 'thug-2',
    name: "Tony Hawk's Underground 2",
    releaseYear: 2004,
    domain: 'activision.com',
  },
  {
    id: 'nfs-u1',
    name: 'Need for Speed: Underground',
    releaseYear: 2003,
    domain: 'ea.com',
  },
  {
    id: 'nfs-u2',
    name: 'Need for Speed: Underground 2',
    releaseYear: 2004,
    domain: 'ea.com',
  },
  {
    id: 'nfs-mw-2005',
    name: 'Need for Speed: Most Wanted',
    releaseYear: 2005,
    domain: 'ea.com',
  },
  {
    id: 'sw-battlefront-1-classic',
    name: 'Star Wars: Battlefront (Classic)',
    releaseYear: 2004,
    domain: 'lucasfilm.com',
  },
  {
    id: 'sw-battlefront-2-classic',
    name: 'Star Wars: Battlefront II (Classic)',
    releaseYear: 2005,
    domain: 'lucasfilm.com',
  },
  {
    id: 'sonic-2',
    name: 'Sonic the Hedgehog 2',
    releaseYear: 1992,
    domain: 'sega.com',
  },
  {
    id: 'mega-man-x',
    name: 'Mega Man X',
    releaseYear: 1993,
    domain: 'capcom.com',
  },
  {
    id: 'dkc-2',
    name: "Donkey Kong Country 2: Diddy's Kong Quest",
    releaseYear: 1995,
    domain: 'nintendo.com',
  },
  {
    id: 'prince-of-persia-sands',
    name: 'Prince of Persia: The Sands of Time',
    releaseYear: 2003,
    domain: 'ubisoft.com',
  },
  {
    id: 'kingdom-hearts-1',
    name: 'Kingdom Hearts',
    releaseYear: 2002,
    domain: 'kingdomhearts.com',
  },
  {
    id: 'max-payne-1',
    name: 'Max Payne',
    releaseYear: 2001,
    domain: 'remedygames.com',
  },

  // Shooter Classics
  {
    id: 'counter-strike-1-6',
    name: 'Counter-Strike 1.6',
    releaseYear: 2003,
    domain: 'counter-strike.net',
  },
  {
    id: 'quake-2',
    name: 'Quake II',
    releaseYear: 1997,
    domain: 'idsoftware.com',
  },
  {
    id: 'unreal-tournament-99',
    name: 'Unreal Tournament',
    releaseYear: 1999,
    domain: 'unrealengine.com',
  },
  {
    id: 'duke-nukem-3d',
    name: 'Duke Nukem 3D',
    releaseYear: 1996,
    domain: '3drealms.com',
  },

  // Arcade Essentials
  {
    id: 'pac-man-original',
    name: 'Pac-Man',
    releaseYear: 1980,
    domain: 'pacman.com',
  },
  {
    id: 'galaga',
    name: 'Galaga',
    releaseYear: 1981,
    domain: 'bandainamcoent.com',
  },
  {
    id: 'dig-dug',
    name: 'Dig Dug',
    releaseYear: 1982,
    domain: 'bandainamcoent.com',
  },
  {
    id: 'asteroids',
    name: 'Asteroids',
    releaseYear: 1979,
    domain: 'atari.com',
  },
  {
    id: 'space-invaders-original',
    name: 'Space Invaders',
    releaseYear: 1978,
    domain: 'taito.co.jp',
  },

  // Modern Hits & Future Legends (2020-2026)
  {
    id: 'it-takes-two',
    name: 'It Takes Two',
    releaseYear: 2021,
    domain: 'hazelight.it',
  },
  {
    id: 'alan-wake-2',
    name: 'Alan Wake 2',
    releaseYear: 2023,
    domain: 'alanwake.com',
  },
  {
    id: 'spiderman-2',
    name: "Marvel's Spider-Man 2",
    releaseYear: 2023,
    domain: 'insomniac.games',
  },
  {
    id: 'metaphor-refantazio',
    name: 'Metaphor: ReFantazio',
    releaseYear: 2024,
    domain: 'atlus.com',
  },
  {
    id: 'astro-bot-2024',
    name: 'Astro Bot',
    releaseYear: 2024,
    domain: 'teamasobi.com',
  },
  {
    id: 'black-myth-wukong',
    name: 'Black Myth: Wukong',
    releaseYear: 2024,
    domain: 'heishenhua.com',
  },
  {
    id: 'expedition-33',
    name: 'Clair Obscur: Expedition 33',
    releaseYear: 2025,
    domain: 'expedition33.com',
  },
  {
    id: 'hades-2',
    name: 'Hades II',
    releaseYear: 2025,
    domain: 'supergiantgames.com',
  },
  {
    id: 'ghost-of-yotei',
    name: 'Ghost of Yotei',
    releaseYear: 2025,
    domain: 'suckerpunch.com',
  },
  {
    id: 'hollow-knight-silksong',
    name: 'Hollow Knight: Silksong',
    releaseYear: 2025,
    domain: 'teamcherry.com.au',
  },
  {
    id: 'death-stranding-2',
    name: 'Death Stranding 2: On the Beach',
    releaseYear: 2025,
    domain: 'kojimaproductions.jp',
  },
  {
    id: 'ac-shadows',
    name: "Assassin's Creed Shadows",
    releaseYear: 2025,
    domain: 'ubisoft.com',
  },
  {
    id: 'gta-6',
    name: 'Grand Theft Auto VI',
    releaseYear: 2026,
    domain: 'rockstargames.com',
  },
  {
    id: 'fable-2026',
    name: 'Fable',
    releaseYear: 2026,
    domain: 'playground-games.com',
  },
  {
    id: 'marvels-wolverine',
    name: "Marvel's Wolverine",
    releaseYear: 2026,
    domain: 'insomniac.games',
  },
  {
    id: 'slay-the-spire-2',
    name: 'Slay the Spire 2',
    releaseYear: 2026,
    domain: 'megacrit.com',
  },
  {
    id: 'subnautica-2',
    name: 'Subnautica 2',
    releaseYear: 2026,
    domain: 'unknownworlds.com',
  },
];
